### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by zz85**
maybe it's time to hurt @mrdoob feelings a little by supporting other jscs presets. the nice thing is that autofixing seems to work across them.

screenshot 2015-06-24 01 17 14
screenshot 2015-06-24 01 17 24
screenshot 2015-06-24 01 17 34

### CODE REVIEW

**Comment by gero3** [comment]
I like this update but the selectbox is a bit too big.

image

And we should keep MDCS as default.

**Comment by zz85** [comment]
haha, yeah i was thinking about an interface to change the present a little. right now it was a quick change to make the select box to match the heading size. it's kind of cute but i'm not sure if it might cause of usability issues yet. if we use a smaller selectbox, we'll need to write some javascript hacks to open the selectbox from the heading...  or maybe we could be arrow buttons eg. << mrdoob >>..

**Comment by gero3** [comment]
Added a small change to make the options smaller the heading.

image

**Comment by zz85** [comment]
hmm... on the mac chrome, nothing seems to have changed 

and the rendering on Firefox on mac seems messed up... 

image

**Comment by gero3** [comment]
Whoops, same problem in firefox windows

image

**Comment by gero3** [comment]
I'll reverse the commit

**Comment by gero3** [comment]
Reversed it

**Pull request merged**
