### PR TITLE
First version of formatting

### PR DESCRIPTION
**Pull request by gero3**
This is a first try at formatting the code.

It uses the latest version of jscs and the old code i had from months ago. It still has som minor issues but it works even on the webglrenderer file altough it takes a second or 2.

A preview is here:
https://preview.c9.io/gero3/mrdoobapproves/index.html

### CODE REVIEW

**Comment by zz85** [comment]
Thanks, I'll take a look at that when I get back home

**Comment by zz85** [comment]
Auto formatting is great... but the issues with white spacing :crying_cat_face: ...

but with formatting, i think it also motives me more code mirror should be use, since it does support the diff plugin too.

**Comment by zz85** [comment]
@gero3 i think we can merge this? we'll can deal with the white-spacing issue later...

**Comment by gero3** [comment]
We should do that since I've been having problems with it before. I'll have to take my time to look at it.

**Comment by zz85** [comment]
checking works great, thanks! would you be making a PR for the mdcs preset in node-jscs too? i'll merge this first and try adding code-mirror support...

**Comment by gero3** [comment]
yep I'll create a PR in node-jscs.

**Comment by zz85** [comment]
:+1: :smile:

**Pull request merged**
