### PR TITLE
add binary operator <<, <<<, >> & >>>

### LINKED ISSUE #26: requreSpaceBefore/AfterBitwise Operators
no good

``` js
( 1<<11 ) - ( 1<<5 ) - 1
```

good

``` js
( 1 << 11 ) - ( 1 << 5 ) - 1
```

we should probably add our own test suite for #22 too...

### PR DESCRIPTION
**Pull request by gero3**
Fixes #26

### CODE REVIEW

**Comment by zz85** [comment]
:+1:  although since we are on binary operations should we also have `&`, `|`, `~`, `^`?

eg.

``` js
a & b
a | b
a ^ b
~ a
a % b
```

or should we simply set `requireSpaceAfterBinaryOperators` to true to accept all binary operators?

**Comment by zz85** [comment]
actually there is a bigger list including..

``` js
&=
/=
+=
-= 
```

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators

**Comment by gero3** [comment]
I just set it to true to allow for all binary operators which would make more sense for this.

**Comment by zz85** [comment]
thanks! :+1:

**Pull request merged**
