### PR TITLE
Improve the formatting of the javascript

### PR DESCRIPTION
**Pull request by gero3**
This is an improved version of the formatting. 

It handles comments in blocks better and spaces between parentheses.

### CODE REVIEW

**Comment by zz85** [comment]
getting better! :)

even though

``` js
for ( var j = 0;j < 100;j ++ )
```

is accepted instead of 

``` js
for ( var j = 0; j < 100; j ++ )
```

**Comment by gero3** [comment]
This is because we don't have any rule that checks that.

We'll have to create one for jscs.

**Comment by zz85** [comment]
perhaps you can try `requireSpaceBetweenArguments`?

**Comment by gero3** [comment]
That only works with callexpressions.

**Comment by zz85** [comment]
ah... i'm surprise there isn't one... ping @mikesherov!

**Comment by mikesherov** [comment]
zz85, yeah, there's no rule for `for` loop spacing. Those technically aren't arguments. We can add one though as @gero3 points out.

**Comment by zz85** [comment]
@mikesherov thanks for dropping by. gero3 should be adding a rule `requireSpacesInForStatement` to node-jscs soon (see #15)

**Pull request merged**
