### PR TITLE
Add some updates to jscs-browser.js

### LINKED ISSUE #4: Whitespaces
the current node-jscs mdcs seems to be accepting

``` js
if (x) {

}
```

as valid when it should be

``` js

if ( x ) {

}
```

i think we need to set `requireSpacesInsideParentheses`?

### PR DESCRIPTION
**Pull request by gero3**
This also adds the formatting for requireSpacesInsideParentheses.
There is also a bit of cleanup with the new version.

fixes #4

### CODE REVIEW

**Comment by zz85** [comment]
thanks! i was also planning to use bower to pull in codemirror, and wonder if i should use bower to pull in https://github.com/gero3/node-jscs/tree/formatter as well...

**Comment by gero3** [comment]
The only thing I'm a bit worried about is that I will be checking in the jscs-browser.js file for that.

**Comment by zz85** [comment]
ok, what we are doing now can work, will optimize process if needed later...

**Comment by zz85** [comment]
@gero3, there still seem to be some errors thrown when trying to run format on code...

**Comment by gero3** [comment]
@zz85 I'll have a look today

**Comment by zz85** [comment]
@gero3 thanks, but please enjoy the new year's eve if you need to!

**Pull request merged**
