### PR TITLE
add save file button

### PR DESCRIPTION
**Pull request by gero3**
I thought it was weird that we had a open file button but not a save file button. So here I added a save button next to the open button

image
.

### CODE REVIEW

**Comment by zz85** [comment]
:+1: i see how this can be useful, esp for a quick save after making some formatting change.

one thing i would desire for this is the ability to save file names.

**Comment by zz85** [comment]
Added filename prompt. Also, I notice safari doesn't seem able to download the file automatically. Not sure if there's a workaround for that.

**Comment by zz85** [comment]
Added workaround for Safari. Merging.

**Comment by gero3** [comment]
nice

**Pull request merged**
